[theme]
base="dark"
primaryColor= "#00FF00"         #The color of buttons and sliders (e.g., Matrix Green)
backgroundColor= "#0E1117"      #Main background color (Dark Grey/Black)
secondaryBackgroundColor = "#262730" #Sidebar and input box background
textColor= "#FAFAFA"            #Text color (White/Off-white)
font= "sans serif"